apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chua-app
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: itemsdb
  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/itemsdb
